# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master


strategy:
  matrix:
    node_8_x_linux:
      imageName: "ubuntu-16.04"
      node_version: 8.x
    node_9_x_linux:
      imageName: "ubuntu-16.04"
      node_version: 9.x
    node_10_x_linux:
      imageName: "ubuntu-16.04"
      node_version: 10.x
    node_8_x_win:
      imageName: "vs2017-win2016"
      node_version: 8.x
    node_9_x_win:
      imageName: "vs2017-win2016"
      node_version: 9.x
    node_10_x_win:
      imageName: "vs2017-win2016"
      node_version: 10.x
    node_8_x_mac:
      imageName: "macOS-10.14"
      node_version: 8.x
    node_9_x_mac:
      imageName: "macOS-10.14"
      node_version: 9.x
    node_10_x_mac:
      imageName: "macOS-10.14"
      node_version: 10.x
    maxParallel: 4

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    npm test
  displayName: 'run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TEST-RESULTS.xml'
  displayName: 'Publish test results'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
  displayName: 'Publish code coverage results'